#!/usr/bin/env ruby

require "bundler/setup"
require 'base'
require 'optparse'
require 'json'
require 'yaml'
require 'active_support/all'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: bitcoin2graphdb -c config.json start"

  opts.on("-c PATH", "--config PATH", "config load path") do |path|
    options[:config] = path
  end
  opts.on("-v", "--verbose", "verbose output") do |v|
    options[:verbose] = v
  end
end.parse!

puts "Welcome to Bitcoin2Graphdb\n\n"

if options[:config]
  if !File.exists?(options[:config])
    puts "File not found: #{options[:config]}"
    exit(1)
  end
  config = YAML.load(File.read(options[:config])).deep_symbolize_keys
  # config = JSON.parse(File.read(options[:config]), {symbolize_names: true})
else
  puts "config file not specified."
  exit(1)
end

$migration = Bitcoin2Graphdb::Migration.new(config)
$migration.run

=begin
command = ARGV.shift

if command == 'console'
  require "irb"
  puts "API is available as $oa:"
  IRB.start
  puts "bye, bye"
elsif command && $oa.respond_to?(command)
  puts "running command '#{command}'"
  puts $oa.send(command, *ARGV).inspect
else
  puts "use 'openassets --help' for help"
end
=end
